package jdbcgui;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Press, Joseph, and Watsy, Farah
 */
public class AddVehicle extends javax.swing.JFrame {

    /**
     * Creates new form AddDepartment
     */
    myDBCon dbCon;

    // constructor for the adddepartment class
    public AddVehicle() {
        initComponents();
        this.setLocationRelativeTo(null); // center form in screen 
        // set all error labels to invisible
        lblPlatenoError.setVisible(false);
        lblMakeError.setVisible(false);
        lblModelError.setVisible(false);
        lblCostError.setVisible(false);
        // populate the combo boxes
        cmbAvailable.removeAllItems();
        cmbIscar.removeAllItems();
        cmbAvailable.addItem("yes");
        cmbAvailable.addItem("no");
        cmbIscar.addItem("yes");
        cmbIscar.addItem("no");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPlateno = new javax.swing.JTextField();
        txtMake = new javax.swing.JTextField();
        txtModel = new javax.swing.JTextField();
        btnAddNewDept = new javax.swing.JButton();
        lblPlatenoError = new javax.swing.JLabel();
        lblModelError = new javax.swing.JLabel();
        lblMakeError = new javax.swing.JLabel();
        cmbIscar = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCost = new javax.swing.JTextField();
        lblCostError = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbAvailable = new javax.swing.JComboBox<>();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add New Employee");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Add New Vehicle");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Plateno:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Make:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Model:");

        txtPlateno.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtMake.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        txtModel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelActionPerformed(evt);
            }
        });

        btnAddNewDept.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAddNewDept.setText("Add New");
        btnAddNewDept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewDeptActionPerformed(evt);
            }
        });

        lblPlatenoError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblPlatenoError.setForeground(new java.awt.Color(255, 0, 0));
        lblPlatenoError.setText("error label");

        lblModelError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblModelError.setForeground(new java.awt.Color(255, 0, 0));
        lblModelError.setText("error label");

        lblMakeError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblMakeError.setForeground(new java.awt.Color(255, 0, 0));
        lblMakeError.setText("error label");

        cmbIscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Is Car:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Cost:");

        txtCost.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtCost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCostActionPerformed(evt);
            }
        });

        lblCostError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblCostError.setForeground(new java.awt.Color(255, 0, 0));
        lblCostError.setText("error label");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Is Available:");

        cmbAvailable.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(16, 16, 16)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAddNewDept)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbIscar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtMake, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPlateno, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCost, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCostError, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblModelError, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMakeError, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPlatenoError, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel1)))
                .addContainerGap(181, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlateno, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(lblPlatenoError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMakeError))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblModelError))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbIscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(lblCostError))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(btnAddNewDept)
                .addGap(0, 184, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelActionPerformed

    // verify valid entry of integer values
    public boolean isInteger(String s) {
        try {
            Integer.parseInt(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }

    // verify valid entry of double values
    public boolean isDouble(String s) {
        try {
            Double.parseDouble(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }

    // clears all of the error labels
    void clearErrorLabels() { // clear all labels used to display error messages 
        lblPlatenoError.setText("");
        lblPlatenoError.setVisible(false);
        lblMakeError.setText("");
        lblMakeError.setVisible(false);
        lblModelError.setText("");
        lblModelError.setVisible(false);
        lblCostError.setText("");
        lblCostError.setVisible(false);
    }

    // validate all user entry before sending new employee details to DB
    boolean isValidData() {
        clearErrorLabels();
        boolean result = true; // assume all details are true, set to false if otherwise 
        // check plateno field
        if (txtPlateno.getText().trim().isEmpty() || txtPlateno.getText().trim().length() > 10 ) {
           
            if (txtPlateno.getText().trim().isEmpty()) {
                lblPlatenoError.setText("Invalid. Cannot be empty.");
            } else if (txtPlateno.getText().trim().length() > 10) {
                lblPlatenoError.setText("Invalid. Must be <10 len.");
            }
            lblPlatenoError.setVisible(true);
            result = false;
        }

        // check make field
        if (txtMake.getText().trim().isEmpty() || (txtMake.getText().trim().length() > 10)) {
            if (txtMake.getText().trim().isEmpty()) {
                lblMakeError.setText("Invalid. Cannot be empty.");
            } else if ((txtMake.getText().trim().length() > 10)) {
                lblMakeError.setText("Invalid. Must be < 10 chars.");
            }
            lblMakeError.setVisible(true);
            result = false;
        }

        // check model field
        if (txtModel.getText().trim().isEmpty() || (txtModel.getText().trim().length() > 10)) {
            if (txtModel.getText().trim().isEmpty()) {
                lblModelError.setText("Invalid. Cannot be empty.");
            } else if (txtModel.getText().trim().length() > 10) {
                lblModelError.setText("Invalid. Must be < 10 chars.");
            }
            lblModelError.setVisible(true);
            result = false;
        }
        
        // check the cost field
        if(txtCost.getText().trim().isEmpty() || !isInteger(txtCost.getText().trim()))
        {
            if(txtCost.getText().trim().isEmpty())
                lblCostError.setText("Invalid. Cannot be empty.");
            else
                lblCostError.setText("Invalid. Must be integer.");
            lblCostError.setVisible(true);
            result = false;
        }
        return result;
    }
    
    // return false if plateno exists already
    boolean validatePlateNotExists(String plateno)
    {
        // select statement
        myDBCon con = new myDBCon();
        ResultSet rs;
        try {
            rs = con.executeStatement("select plateno from vehicle where plateno = '" + plateno + "'");
            if(rs.next()){
                return true;
            }
        }
        catch(Exception e) {
            System.out.println(e);
        }
        return false;
    }

    // clear the input boxes to refresh
    void clearInputBoxes() { // clear for every new entry 
        txtPlateno.setText("");
        txtMake.setText("");
        txtModel.setText("");
        txtCost.setText("");
        cmbAvailable.setSelectedIndex(0);
        cmbIscar.setSelectedIndex(0);
    }
    
    private String isCar() {
        if(cmbIscar.getSelectedItem().equals("yes"))
            return "1";
        return "0";
    }
    private String isAvailable() {
        if(cmbAvailable.getSelectedItem().equals("yes"))
            return "1";
        return "0";
    }
    
    // method invoked when user adds new department
    private void btnAddNewDeptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewDeptActionPerformed
        // TODO add your handling code here:
        try {
            // only perform after data validation
            if (isValidData() && !validatePlateNotExists(txtPlateno.getText().trim())) {
                // if new employee details are valid, then add new employee to DB
                dbCon = new myDBCon();
                // prepare the SQL statement
                String prepSQL = "INSERT INTO vehicle VALUES ('"
                        + txtPlateno.getText().trim() + "', "
                        + "'" + txtMake.getText().toUpperCase() + "', "
                        + "'" + txtModel.getText().toUpperCase() + "', "
                        + isCar() + ", "
                        + txtCost.getText() + ", " 
                        + isAvailable() + ")";
                
                int result = dbCon.executePrepared(prepSQL);
                if (result > 0) {
                    javax.swing.JLabel label = new javax.swing.JLabel("New vehicle added successfully.");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                    clearInputBoxes();
                } else {
                }
            } else {
                // display boxes for the respective errors
                if (validatePlateNotExists(txtPlateno.getText().trim())) {
                    javax.swing.JLabel label = new javax.swing.JLabel("Plateno already exists. Use a different plate number.");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    javax.swing.JLabel label = new javax.swing.JLabel("Please fix validation errors...");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);
                }

            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error adding new department.");
        }
    }//GEN-LAST:event_btnAddNewDeptActionPerformed

    private void txtCostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCostActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewDept;
    private javax.swing.JComboBox<String> cmbAvailable;
    private javax.swing.JComboBox<String> cmbIscar;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblCostError;
    private javax.swing.JLabel lblMakeError;
    private javax.swing.JLabel lblModelError;
    private javax.swing.JLabel lblPlatenoError;
    private javax.swing.JTextField txtCost;
    private javax.swing.JTextField txtMake;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtPlateno;
    // End of variables declaration//GEN-END:variables
}
